return {
	go = "gopls",
	-- python = "pyright",
	python = "basedpyright",
	lua = "lua_ls",
	javascript = "ts_ls",
	ruby = "solargraph",
	java = "jdtls",
	groovy = "groovyls",
	xml = "lemminx",
	rust = "rust_analyzer",
	starlark = "starlark_rust",
	dart = "dartls",
	json = "jsonls",
}
