-- TODO: After the refactor of certain plugins, this list should be updated to reflect the new structure.
return {
	{ import = "plugins.avante" },
	{ import = "plugins.neo-tree" },
	{ import = "plugins.mason" },
	{ import = "plugins.treesitter" },
	{ import = "plugins.themes" },
	{ import = "plugins.overseer" },
	{ import = "plugins.neotest" },
	{ import = "plugins.nvim-cmp" },
	{ import = "plugins.neodev" },
	{ import = "plugins.lualine" },
	{ import = "plugins.noice" },
	{ import = "plugins.neogit" },
	{ import = "plugins.mini" },
	{ import = "plugins.telescope" },
	{ import = "plugins.nvim-spectre" },
	{ import = "plugins.vim-visual-multi" },
	{ import = "plugins.copilot" },
	{ import = "plugins.nvim-window-picker" },
	{ import = "plugins.whichkey" },
	{ import = "plugins.obsidian" },
	{ import = "plugins.markdown" },
	{ import = "plugins.trouble" },
	{ import = "plugins.aerial" },
	{ import = "plugins.lsp_signature" },

	-- Windows, Panes, Splits, Buffers Management
	{ import = "plugins.windows" },
	{ import = "plugins.edgy" },
	{ import = "plugins.bufresize" },
	{ import = "plugins.gitsigns" },
}
