-- TODO: After the refactor of certain plugins, this list should be updated to reflect the new structure.
return {
	{ import = "plugins.avante" },
	{ import = "plugins.neo-tree" },
	{ import = "plugins.mason" },
	{ import = "plugins.treesitter" },
	{ import = "plugins.gruvbox" },
	{ import = "plugins.overseer" },
	{ import = "plugins.neotest" },
	{ import = "plugins.nvim-cmp" },
	{ import = "plugins.neodev" },
	{ import = "plugins.lualine" },
	{ import = "plugins.noice" },
	{ import = "plugins.neogit" },
	{ import = "plugins.vim-surround" },
	{ import = "plugins.vim-repeat" },
	{ import = "plugins.nvim-autopairs" },
	{ import = "plugins.fzf-lua" },
	{ import = "plugins.nvim-spectre" },
	{ import = "plugins.vim-visual-multi" },
	{ import = "plugins.comment" },
	{ import = "plugins.copilot" },
}
